; ESP32 Node-1 — Phát WiFi AP "ESP32-Node-1", lưu file SPIFFS
[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
board_build.partitions = no_ota.csv
build_flags =
    -DBOARD_NODE=1
